name: Deploy to Beta VM

on:
  push:
    branches: [ "main", "beta" ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up the correct version of Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Build project
      - name: Build with Gradle
        run: ./gradlew clean bootJar

      # 4. Deploy to Beta environment (only if running on beta branch)
      - name: Deploy to Beta
        if: github.ref == 'refs/heads/beta'
        env:
          BETA_HOST: ${{ secrets.BETA_HOST }}
          BETA_USER: ${{ secrets.BETA_USER }}
          BETA_SSH_KEY: ${{ secrets.BETA_SSH_KEY }}
        run: |
          echo "Deploying to Beta environment..."

          # Configure SSH
          mkdir -p ~/.ssh
          echo "$BETA_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Transfer the jar to Beta server using scp
          scp -o StrictHostKeyChecking=no build/libs/*.jar $BETA_USER@$BETA_HOST:/opt/458abroad/abroad-0.0.1-SNAPSHOT.jar

          # Restart the Beta service via SSH
          ssh -o StrictHostKeyChecking=no $BETA_USER@$BETA_HOST \
            "sudo systemctl restart 458abroad.service"

      # 5. Deploy to Production environment (only if running on main branch)
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        env:
          PROD_HOST: ${{ secrets.BETA_HOST }}
          PROD_USER: ${{ secrets.BETA_USER }}
          PROD_SSH_KEY: ${{ secrets.BETA_SSH_KEY }}
        run: |
          echo "Deploying to Production environment..."

          # Configure SSH
          mkdir -p ~/.ssh
          echo "$PROD_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Transfer the jar to Production server using scp
          scp -o StrictHostKeyChecking=no build/libs/*.jar $BETA_USER@$BETA_HOST:/opt/458abroad/abroad-0.0.1-SNAPSHOT.jar

          # Restart the Production service via SSH
          ssh -o StrictHostKeyChecking=no $PROD_USER@$PROD_HOST \
            "sudo systemctl restart 458abroad.service"